### PR TITLE
Updates Protocol related sections

### PR DESCRIPTION
**Pull request by matsusato3**

### CODE REVIEW

**Comment by lbertz02** [comment]
Looks good.

**Comment by lbertz02** [comment]
Shall we merge?

**Comment by matsusato3** [comment]
Please.

Sent from my iPhone

2017/03/10 8:31、Lyle Bertz <notifications@github.com> のメッセージ:

> Shall we merge?
>

**Comment by matsusato3** [comment]
Didn't you merge?

**Pull request merged**
