### PR TITLE
Updates IM with text and comments from CEP. Adds Domain-reference.

### PR DESCRIPTION
**Pull request by matsusato3**

### CODE REVIEW

**Comment by lbertz02** [comment]
nits
Line 675 - 'grous' to 'groups'
Line 891 - Add "Order values MUST be unique within the Rules list."
Line 906 - Add "Action-Order values MUST be unique within the Actions list."

Policies (Rules) follow 'OR' principal logic.  In the case of a Policy-Group will we permit the presence of Order values that are the same for two Rules in different Policies?   If so, should we warn authors that the system is unpredictable?

Line 1065, 1065, 1075, 1275 - 'context' to 'Context'
Line 1466 - 'assign' to 'assigns'
Line 1502 - 'detail' to 'detailed'
Line 1513 - 'thereby no' to 'thereby has no'
Line 1539 - 'However it is risked that' to 'However, risks exists, for example '

**Comment by lbertz02** [comment]
FYI - The line numbers I quote above are with the merged view and NOT the diff file view.  Sorry about that!

**Comment by matsusato3** [comment]
> 
> FYI - The line numbers I quote above are with the merged view and NOT the diff file view. Sorry about that!

No problem. ;-)

**Comment by matsusato3** [comment]
> Policies (Rules) follow 'OR' principal logic. In the case of a Policy-Group will we permit the presence of Order values that are the same for two Rules in different Policies? If so, should we warn authors that the system is unpredictable?
> 

Hmm.. or, should we explain that Rules of Policies within a Policy-group must be coexist in no order sensitive?

**Comment by lbertz02** [comment]
Fair point but in underlying DPN implementations such as OpenFlow they do adhere to order but it is okay to have them with the same order value - just expect them to be nondeterministic for values of the same Order.?

________________________________

**Comment by matsusato3** [comment]
> Fair point but in underlying DPN implementations such as OpenFlow they do adhere to order but it is okay to have them with the same order value - just expect them to be nondeterministic for values of the same Order.?
> 

It might be a multiple DPNs case where the rules in each Policy could be implemented to different DPNs.

**Comment by lbertz02** [comment]
Agreed.  This is a non-trivial matter but I think it is something we must point out as oppose to restricting.   I would add language that notes

“When using Policy-groups or Vports note that multiple Rules are joined via the ‘OR’ principal logic where they may have the same Order value.  Which specific Rule is tested first is outside of the scope of this specification as it relies on the Agent and underlying DPN implementation.  If an Operator wishes to avoid conflict they MUST provision the Order values in Rules as a globally unique set of values.”

I am just not sure where to place such language it the document.  Maybe the Attribute / Application section?

**Comment by matsusato3** [comment]
> Agreed. This is a non-trivial matter but I think it is something we must point out as oppose to restricting. I would add language that notes 
> 
> “When using Policy-groups or Vports note that multiple Rules are joined via the ‘OR’ principal logic where they may have the same Order value. Which specific Rule is tested first is outside of the scope of this specification as it relies on the Agent and underlying DPN implementation. If an Operator wishes to avoid conflict they MUST provision the Order values in Rules as a globally unique set of values.” 
> 

I think there’s another case where Policies could be instantiated as usual policy-map configurations on a router.
Each policy-map could confine its order in it.

> I am just not sure where to place such language it the document. Maybe the Attribute / Application section? 

I agree, that section looks fit to that.

**Comment by lbertz02** [comment]
Comments inline

**Pull request merged**
