### PR TITLE
Introduction update

### PR DESCRIPTION
**Pull request by matsusato3**

### CODE REVIEW

**Comment by lbertz02** [comment]
Lines 244 to 245 - I don't understand "along with
consequence of the control plane."  what is the consequence?

No other issues with the merge - just some minor editorial nits:
Line 207 - Change 'export' to 'exports'
Line 223 - Change 'concept' to 'concepts'
Line 225 - Change 'enables' to 'enable'
Line 232 - Capitalize 'policy' as it is capitalized on Line 230
Line 250 - Change 'occurs' to 'occur'
Line 258 - Change 'configure DPN' to 'configure a DPN'
Line 264 - Change 'and' to 'or'

**Comment by matsusato3** [comment]
> Lines 244 to 245 - I don't understand "along with
> consequence of the control plane." what is the consequence?
> 

It just means the consequence of that mobile control-plane nodes create tunnel endpoints for a session and use GTP-C signaling to exchange them.

**Comment by matsusato3** [comment]
> Line 225 - Change 'enables' to 'enable'

This “enables" is about “an interface”. Is that correct?

**Comment by lbertz02** [comment]
Per your comments 
Lines 244 to 245 - Ok, no issues then.  Not sure it is a readability issue and will not recommend a change.
Line 225 - My mistake - please disregard.

**Pull request merged**
