### PR TITLE
Yangupdates

### PR DESCRIPTION
**Pull request by lbertz02**
If we are okay with this branch and especially the YANG requests. I would like to merge it with the main.

### CODE REVIEW

**Comment by matsusato3** [comment]
I don't know why the sections of search-order and Policy and Runtime Data are needed.

**Comment by matsusato3** [comment]
Please use v05 xml file.

**Comment by lbertz02** [comment]
search-order  and Policy and Runtime Data provide concrete methods of where attributes are searched in the information model.  Having a consistent order ensures that Clients get consistent results and Agents have deterministic (easier to code) behavior.

**Comment by lbertz02** [comment]
wrt the v05 I will create a new branch and move the updates over.  Before I do please look at #30.  If we are okay with #30 I can reject the 04 changes in this branch and then merge it which will be a bit easier to track on git.

**Pull request closed without merging**
